config/routes.rb
Attendance::Application.routes.draw do
  resources :attendance_entries

  get "home/index"

  resources :employees do
    resources :presences
  end
  root :to => 'home#index'
  

end

app/models/attendance_entry.rb
class AttendanceEntry < ActiveRecord::Base
  belongs_to :employee
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates_presence_of :first_name, :last_name, :designation, :date_of_birth, :sex
  has_many :presences
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attendance_entries_controller.rb
class AttendanceEntriesController < ApplicationController
  # GET /attendance_entries
  # GET /attendance_entries.json
  def index
    @attendance_entries = AttendanceEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attendance_entries }
    end
  end

  # GET /attendance_entries/1
  # GET /attendance_entries/1.json
  def show
    @attendance_entry = AttendanceEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attendance_entry }
    end
  end

  # GET /attendance_entries/new
  # GET /attendance_entries/new.json
  def new
    @attendance_entry = AttendanceEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attendance_entry }
    end
  end

  # GET /attendance_entries/1/edit
  def edit
    @attendance_entry = AttendanceEntry.find(params[:id])
  end

  # POST /attendance_entries
  # POST /attendance_entries.json
  def create
    @attendance_entry = AttendanceEntry.new(params[:attendance_entry])

    respond_to do |format|
      if @attendance_entry.save
        format.html { redirect_to @attendance_entry, notice: 'Attendance entry was successfully created.' }
        format.json { render json: @attendance_entry, status: :created, location: @attendance_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @attendance_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attendance_entries/1
  # PUT /attendance_entries/1.json
  def update
    @attendance_entry = AttendanceEntry.find(params[:id])

    respond_to do |format|
      if @attendance_entry.update_attributes(params[:attendance_entry])
        format.html { redirect_to @attendance_entry, notice: 'Attendance entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attendance_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendance_entries/1
  # DELETE /attendance_entries/1.json
  def destroy
    @attendance_entry = AttendanceEntry.find(params[:id])
    @attendance_entry.destroy

    respond_to do |format|
      format.html { redirect_to attendance_entries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_entries_helper.rb
module AttendanceEntriesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/attendance_entries/_form.html.erb
<%= form_for(@attendance_entry) do |f| %>
  <% if @attendance_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendance_entry.errors.count, "error") %> prohibited this attendance_entry from being saved:</h2>

      <ul>
      <% @attendance_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br />
    <%= f.date_select :day %>
  </div>
  <div class="field">
    <%= f.label :in_time %><br />
    <%= f.datetime_select :in_time %>
  </div>
  <div class="field">
    <%= f.label :out_time %><br />
    <%= f.datetime_select :out_time %>
  </div>
  <div class="field">
    <%= f.label :present %><br />
    <%= f.check_box :present %>
  </div>
  <div class="field">
    <%= f.label :employee %><br />
    <%= f.text_field :employee %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendance_entries/edit.html.erb
<h1>Editing attendance_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendance_entry %> |
<%= link_to 'Back', attendance_entries_path %>

app/views/attendance_entries/index.html.erb
<h1>Listing attendance_entries</h1>

<table>
  <tr>
    <th>Day</th>
    <th>In time</th>
    <th>Out time</th>
    <th>Present</th>
    <th>Employee</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attendance_entries.each do |attendance_entry| %>
  <tr>
    <td><%= attendance_entry.day %></td>
    <td><%= attendance_entry.in_time %></td>
    <td><%= attendance_entry.out_time %></td>
    <td><%= attendance_entry.present %></td>
    <td><%= attendance_entry.employee %></td>
    <td><%= link_to 'Show', attendance_entry %></td>
    <td><%= link_to 'Edit', edit_attendance_entry_path(attendance_entry) %></td>
    <td><%= link_to 'Destroy', attendance_entry, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attendance entry', new_attendance_entry_path %>

app/views/attendance_entries/new.html.erb
<h1>New attendance_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', attendance_entries_path %>

app/views/attendance_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Day:</b>
  <%= @attendance_entry.day %>
</p>

<p>
  <b>In time:</b>
  <%= @attendance_entry.in_time %>
</p>

<p>
  <b>Out time:</b>
  <%= @attendance_entry.out_time %>
</p>

<p>
  <b>Present:</b>
  <%= @attendance_entry.present %>
</p>

<p>
  <b>Employee:</b>
  <%= @attendance_entry.employee %>
</p>


<%= link_to 'Edit', edit_attendance_entry_path(@attendance_entry) %> |
<%= link_to 'Back', attendance_entries_path %>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :designation %><br />
    <%= f.text_field :designation %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.select :sex, options_for_select([['Male', 'male'], ['Female', 'female']]) %>
  </div>
  <div class="field">
    <%= f.label :employee_code %><br />
    <%= f.text_field :employee_code %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth, :start_year => 1947, :end_year => Time.now.year, :order => [:day, :month, :year]%>
  </div>
  <div class="field">
    <%= f.label :remarks %><br />
    <%= f.text_area :remarks %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Designation</th>
    <th>Sex</th>
    <th>Employee code</th>
    <th>Date of birth</th>
    <th>Remarks</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.first_name %></td>
    <td><%= employee.last_name %></td>
    <td><%= employee.designation %></td>
    <td><%= employee.sex %></td>
    <td><%= employee.employee_code %></td>
    <td><%= employee.date_of_birth %></td>
    <td><%= employee.remarks %></td>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', employee, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @employee.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @employee.last_name %>
</p>

<p>
  <b>Designation:</b>
  <%= @employee.designation %>
</p>

<p>
  <b>Sex:</b>
  <%= @employee.sex %>
</p>

<p>
  <b>Employee code:</b>
  <%= @employee.employee_code %>
</p>

<p>
  <b>Date of birth:</b>
  <%= @employee.date_of_birth %>
</p>

<p>
  <b>Remarks:</b>
  <%= @employee.remarks %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/home/index.html.erb
<h1>Home</h1>
<p> <%= link_to "Employee Listing", employees_path %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Attendance</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>